order.lever = 2
order.fundingRateThreshold = 0.005
order.openPrincipal = 10

bitget.apiKey =
bitget.secretKey =
bitget.passphrase =

log.logName = log/default.log
log.logSize = 100M
log.logLevel = notice

# bark
bark.server =
