order.lever = 100
order.fundingRateThreshold = 0.001

bitget.apiKey =
bitget.secretKey =
bitget.passphrase =

log.logName = log/default.log
log.logSize = 100M
log.logLevel = notice

# bark
bark.server =
